# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
