# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='request_id',
            field=models.CharField(default='RQ0', max_length=50),
            preserve_default=False,
        ),
    ]
