# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizz', '0002_price_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100),
            preserve_default=False,
        ),
    ]
