# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizz', '0002_auto_20171222_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_USD',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
